name: CI

on:
  pull_request:
    branches: [main]

jobs:
  tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26'

      - name: Tidy
        run: go mod tidy

      - name: Check go.mod and go.sum are clean
        run: git diff --exit-code go.mod go.sum

  format:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26'

      - name: Format
        run: go fmt ./...

      - name: Check formatting
        run: git diff --exit-code

  lint:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26'

      - name: Lint
        run: go vet ./...

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26'

      - name: Build
        run: go build ./...

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26'

      - name: Test
        run: go test -race -count=1 ./...
